# This workflow will deploy Cloud Surface_Go - source code on (https://dashboard.balena-cloud.com/apps) when a commit is pushed to the "main" branch
#
# Overview:
#
#  Deploy it to Cloud Surface_Go on https://api.balena-cloud.com/
#
# To configure this workflow:
#
#  Create and configure Workload Identity Federation for GitHub (https://github.com/Ghepes/Surface_Go/new/main?filename=.github%2Fworkflows)
#
#
#    Surface_Go Storage
#      roles/storage.object
#
# For more support on how to run this workflow, please visit https://github.com/Ghepes/Surface_Go/new/main/actions/
#

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - "main"
      - "master"

jobs:
  flowzone:
    name: Surface_Go
    uses: product-os/flowzone/.github/workflows/Surface_Go.yml@master
    secrets: inherit
    with:
      balena_slugs: balena_io_examples/balena-python-hello-world

# NOTE: If required, update to the appropriate source folder


